services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}   
      POSTGRES_DB: ${POSTGRES_DB}  
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:3
    entrypoint: ["sh", "-c", "sleep 5 && python server.py"]
    ports:
      - "8010:8888"
    environment:
      DB_USER: ${POSTGRES_USER}  
      DB_PASSWORD: ${POSTGRES_PASSWORD}   
      DB_NAME: ${POSTGRES_DB} 
      DB_HOST: db
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db

volumes:
  db_data:
